### ISSUE TITLE
Fails to build with vala 0.48

### ISSUE THREAD

**Issue by City-busz** [GijsGoudzwaard/Image-Optimizer#48]
The application fails to build with vala 0.48. The build log:
```
valac -C --pkg granite --pkg gtk+-3.0 --pkg glib-2.0 --pkg gee-0.8 --color=always --directory com.github.gijsgoudzwaard.image-optimizer@exe --basedir ../Image-Optimizer/ --gresources=../Image-Optimizer/data/com.github.gijsgoudzwaard.image-optimizer.gresource.xml ../Image-Optimizer/src/Application.vala ../Image-Optimizer/src/MainWindow.vala ../Image-Optimizer/src/Widgets/Toolbar.vala ../Image-Optimizer/src/Widgets/UploadScreen.vala ../Image-Optimizer/src/Widgets/List.vala ../Image-Optimizer/src/Utils/Utils.vala ../Image-Optimizer/src/Utils/Image.vala ../Image-Optimizer/src/Utils/Optimizer.vala ../Image-Optimizer/src/Utils/JpegOptim.vala ../Image-Optimizer/src/Utils/OptiPng.vala ../Image-Optimizer/src/Constants/Stylesheet.vala
../Image-Optimizer/src/Widgets/UploadScreen.vala:34.5-34.36: warning: `Gtk.Button.set_focus_on_click' has been deprecated since 3.20
../Image-Optimizer/src/Widgets/List.vala:26.5-26.41: warning: `Gtk.Button.set_focus_on_click' has been deprecated since 3.20
../Image-Optimizer/src/Utils/JpegOptim.vala:50.5-50.21: warning: delegates with scope="async" must be owned
    ThreadFunc<void*> run = () => {
    ^^^^^^^^^^^^^^^^^
../Image-Optimizer/src/Utils/JpegOptim.vala:76.5-76.9: error: yield statement not available outside async method
    yield;
    ^^^^^
../Image-Optimizer/src/Utils/OptiPng.vala:50.5-50.21: warning: delegates with scope="async" must be owned
    ThreadFunc<void*> run = () => {
    ^^^^^^^^^^^^^^^^^
../Image-Optimizer/src/Utils/OptiPng.vala:80.5-80.9: error: yield statement not available outside async method
    yield;
    ^^^^^
../Image-Optimizer/src/MainWindow.vala:58.5-58.24: warning: Assignment to same variable
    this.images = images;
    ^^^^^^^^^^^^^^^^^^^^
../Image-Optimizer/src/Application.vala:22.5-22.19: warning: `Gtk.Application.add_accelerator' has been deprecated since 3.14
Compilation failed: 2 error(s), 6 warning(s)
```

**Comment by GijsGoudzwaard** [comment]
Should be fixed now.

**Comment by City-busz** [comment]
I still experience this issue, but I cannot reopen the issue.

**Comment by GijsGoudzwaard** [comment]
Added fix in https://github.com/GijsGoudzwaard/Image-Optimizer/releases/tag/0.1.18 Will release version asap on elementary store.
